djangoapp/pihome/urls.py
from django.urls import path, include
from pihome.views import (
    index, 
    lightRoom, 
    teste, 
    execute_mqtt_action, 
    test_mqtt_connection, 
    save_mqtt_button, 
    update_mqtt_button, 
    delete_mqtt_button, 
    create_user, 
    logout_view,
    signup_or_login_redirect,
    project_info,
    license_view,
    group_view,
    integrator_project_view,
    pi_db_list,
    PiDBList,
)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


app_name = 'pihome'

urlpatterns = [
    path('', signup_or_login_redirect, name='signup_or_login_redirect'),
    path('index/', index, name='index'),
    path('logout/', logout_view, name='logout'),
    path('teste/', teste, name='teste'),
    path('light-room/', lightRoom, name='lightRoom'),
    path('execute-mqtt-action/', execute_mqtt_action, name='execute_mqtt_action'),
    path('test-mqtt-connection/', test_mqtt_connection, name='test_mqtt_connection'),
    path('accounts/', include('allauth.urls')),
    path('accounts/signup/', create_user, name='account_signup'),
    path('save-mqtt-button/', save_mqtt_button, name='save_mqtt_button'),
    path('update-mqtt-button/<int:button_id>/', update_mqtt_button, name='update_mqtt_button'),
    path('delete-mqtt-button/<int:id>/', delete_mqtt_button, name='delete_mqtt_button'),
    path('create-user/', create_user, name='create_user'),
    path('project-info/', project_info, name='project_info'),
    path('license/', license_view, name='license'),
    path('group/', group_view, name='group'),
    path('integrator-project/', integrator_project_view, name='integrator_project'),
    path('api/devices/', pi_db_list, name='pi_db_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # Include allauth URLs
    path('', include('pihome.urls')),  # Include pihome app URLs
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/pihome/models.py
from django.db import models
from django.core.exceptions import ValidationError

class Action(models.Model):
    id = models.AutoField(primary_key=True)
    action = models.TextField(null=True, blank=True)  # Permitir valores nulos
    date = models.DateField()
    time = models.TimeField()
    topic = models.TextField(null=True, blank=True)  # Permitir valores nulos

    def clean(self):
        if self.action not in ["ON", "OFF"]:
            raise ValidationError("Action must be 'ON' or 'OFF'")

    def __str__(self):
        return f"Action on {self.date} at {self.time} with action: {self.action} on topic: {self.topic}"

class MQTTButton(models.Model):
    name = models.CharField(max_length=255)
    ip = models.CharField(max_length=255)
    port = models.IntegerField()
    topic = models.CharField(max_length=255)
    message = models.CharField(null=True, blank=True, max_length=200)  # Add the message field
    create_button = models.BooleanField(default=False)

    def __str__(self):
        return f"Button {self.name} for topic {self.topic}"

djangoapp/pihome/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseForbidden
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import user_passes_test, login_required 
from django.contrib.auth.views import LoginView
from django.urls import reverse
from pihome.models import Action, MQTTButton
from django.utils import timezone
import os
import paho.mqtt.client as mqtt
import json
from django import forms
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from .models import MQTTButton
from .serializers import MQTTButtonSerializer

def block_signup_if_users_exist(view_func):
    """Decorator to block access to signup if users already exist."""
    def _wrapped_view(request, *args, **kwargs):
        if User.objects.exists():
            # Retorna uma página de acesso negado
            return HttpResponseForbidden("Access denied: User creation is not allowed as a user already exists.")
        return view_func(request, *args, **kwargs)
    return _wrapped_view

def logout_view(request):
    logout(request)
    return redirect('pihome:index')

@login_required
def index(request):
    buttons = MQTTButton.objects.all()
    users = User.objects.all()  # Query all users
    return render(request, 'pihome/index.html', {'buttons': buttons, 'users': users})

def lightRoom(request):
    if request.method == 'POST':
        mqtt_client = mqtt.Client(client_id='djangoapp', protocol=mqtt.MQTTv5)
        mqtt_client.connect('localhost', 1883, 60)
        mqtt_client.publish('cmnd/messages/POWER', 'TOGGLE')

        return JsonResponse({'message': 'Light toggled and action saved'})
    return JsonResponse({'error': 'Invalid request'}, status=400)

def teste(request):
    return render(request, 'pihome/teste.html')

def execute_mqtt_action(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            ip = data.get('ip')
            port = int(data.get('port'))
            topic = data.get('topic')
            message = data.get('message', 'TOGGLE')

            if not ip or not port or not topic:
                return JsonResponse({'error': 'Missing required parameters'}, status=400)

            mqtt_client = mqtt.Client(client_id='web_client', protocol=mqtt.MQTTv5)
            mqtt_client.connect(ip, port, 60)
            mqtt_client.publish(topic, message)

            return JsonResponse({'message': f'Message "{message}" sent to topic "{topic}" on broker "{ip}:{port}"'})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    return JsonResponse({'error': 'Invalid request'}, status=400)

def test_mqtt_connection(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            ip = data.get('ip')
            port = int(data.get('port'))

            mqtt_client = mqtt.Client(client_id='test_client', protocol=mqtt.MQTTv5)
            mqtt_client.connect(ip, port, 60)
            mqtt_client.disconnect()

            return JsonResponse({'message': 'Connection successful'})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    return JsonResponse({'error': 'Invalid request'}, status=400)

@csrf_exempt
def save_mqtt_button(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            name = data.get('name')
            ip = data.get('ip')
            port = data.get('port')
            topic = data.get('topic')
            message = data.get('message')  # Capture the message field

            if name and ip and port and topic and message:
                MQTTButton.objects.create(name=name, ip=ip, port=port, topic=topic, message=message)
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': 'Missing required fields.'}, status=400)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=405)

@csrf_exempt
def update_mqtt_button(request, button_id):  # Ensure the parameter name matches the URL pattern
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            name = data.get('name')
            ip = data.get('ip')
            port = data.get('port')
            topic = data.get('topic')
            message = data.get('message')  # Capture the message field

            button = MQTTButton.objects.get(id=button_id)  # Use the correct parameter name
            button.name = name
            button.ip = ip
            button.port = port
            button.topic = topic
            button.message = message
            button.save()

            return JsonResponse({'status': 'success'})
        except MQTTButton.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Button not found.'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=405)

def delete_mqtt_button(request, id):
    if request.method == 'POST':
        try:
            button = MQTTButton.objects.get(id=id)
            button.delete()
            return JsonResponse({'status': 'success'})
        except MQTTButton.DoesNotExist:
            return JsonResponse({'status': 'failed', 'error': 'Button not found'}, status=404)
    return JsonResponse({'status': 'failed'}, status=400)

def signup_or_login_redirect(request):
    # Verifica se há usuários no banco de dados
    if not User.objects.exists():
        return redirect('account_signup')  # Redireciona para a tela de criação de usuário
    if request.user.is_authenticated:
        return redirect('pihome:index')  # Redireciona para a página inicial se o usuário já estiver autenticado
    return redirect('account_login')  # Redireciona para a tela de login

@block_signup_if_users_exist
def create_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if not User.objects.exists():  # Primeiro usuário se torna superuser
                user.is_superuser = True
                user.is_staff = True
            user.save()
            login(request, user)  # Loga automaticamente o primeiro usuário
            return redirect('index')  # Redireciona para a página inicial
    else:
        form = UserCreationForm()
    return render(request, 'pihome/create_user.html', {'form': form})

@user_passes_test(lambda u: not User.objects.exists(), login_url='account_login')
def signup_redirect(request):
    # Redireciona para a tela de criação de usuário se não houver usuários
    return redirect('account_signup')

def password_reset_form_view(request):
    # Verifica se há usuários no banco de dados
    allow_user_creation = not User.objects.exists()  # False se já houver usuários
    return render(request, 'registration/password_reset_form.html', {
        'allow_user_creation': allow_user_creation,  # Passa a variável ao template
    })

def project_info(request):
    return render(request, 'pihome/project_info.html')

def license_view(request):
    return render(request, 'pihome/license.html')

def group_view(request):
    return render(request, 'pihome/group.html')

def integrator_project_view(request):
    return render(request, 'pihome/integrator_project.html')
@login_required
@api_view(['GET', 'POST'])
def pi_db_list(request):
    """
    Handle GET and POST requests for MQTTButton objects.
    """
    if request.method == 'GET':
        # Retrieve all MQTTButton objects
        buttons = MQTTButton.objects.all()
        serializer = MQTTButtonSerializer(buttons, many=True)
        return Response({"devices": serializer.data})

    elif request.method == 'POST':
        # Update an existing MQTTButton object
        serializer = MQTTButtonSerializer(data=request.data)
        if serializer.is_valid():
            try:
                button = MQTTButton.objects.get(id=request.data.get('id'))
                for attr, value in serializer.validated_data.items():
                    setattr(button, attr, value)
                button.save()
                return Response({"status": "success", "message": "Device updated successfully."})
            except MQTTButton.DoesNotExist:
                return Response({"status": "error", "message": "Device not found."}, status=404)
        return Response(serializer.errors, status=400)
@login_required
class PiDBList(APIView):
    """
    API view to retrieve and update MQTTButton objects.
    """

    def get(self, request):
        """
        Handle GET requests to retrieve all MQTTButton objects.
        """
        filter_param = request.GET.get('filter', None)
        buttons = MQTTButton.objects.all()
        serializer = MQTTButtonSerializer(buttons, many=True)
        return Response({"filter": filter_param, "devices": serializer.data})

    def post(self, request):
        """
        Handle POST requests to update an MQTTButton object.
        """
        serializer = MQTTButtonSerializer(data=request.data)
        if serializer.is_valid():
            try:
                button = MQTTButton.objects.get(id=request.data.get('id'))
                for attr, value in serializer.validated_data.items():
                    setattr(button, attr, value)
                button.save()

djangoapp/pihome/templates/pihome/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Authentication</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="auth-container">
        <h1>Welcome to PiHome</h1>
        <form method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
        <a href="{% url 'signup' %}">Sign up</a>
    </div>
</body>
</html>

djangoapp/pihome/templates/pihome/contact_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Administrator</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="auth-container">
        <h2>Access Denied</h2>
        <p>There is already a user registered in the system.</p>
        <p>If you need access, please contact the system administrator.</p>
        <a href="{% url 'pihome:login' %}" class="primary-btn">Back to Login</a>
    </div>
</body>
</html>

djangoapp/pihome/templates/pihome/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
</head>
<body>
    <div class="auth-container">
        <h2>Create User</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="primary-btn">Create User</button>
        </form>
    </div>
</body>
</html>

djangoapp/pihome/templates/pihome/group.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grupo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">PiHome</a>
            <a href="{% url 'pihome:index' %}" class="btn btn-outline-light">Voltar</a>
        </div>
    </nav>

    <div class="container mt-5 pt-5">
        <h2 class="text-center mb-4">Grupo</h2>
        <div class="row">
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/wanderson.jpg' %}" alt="Wanderson Barbosa" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Wanderson Barbosa</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/nicole.jpg' %}" alt="Nicole Calegari de Lima" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Nicole Calegari de Lima</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/celio.jpg' %}" alt="Celio Edgar Rebechi" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Celio Edgar Rebechi</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/paulo.jpg' %}" alt="Paulo Eduardo Baroni" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Paulo Eduardo Baroni</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/carlos.jpg' %}" alt="Carlos Eduardo Cioffi Reigota" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Carlos Eduardo Cioffi Reigota</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/tiago.jpg' %}" alt="Tiago Giglia Manoel" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Tiago Giglia Manoel</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/sergio.jpg' %}" alt="Sergio Rebechi" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Sergio Rebechi</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'images/jose.jpg' %}" alt="Jose Roberto de Andrade Salgueiro" class="img-fluid rounded-circle" style="width: 150px; height: 150px;">
                <h5 class="mt-2">Jose Roberto de Andrade Salgueiro</h5>
                <p>Email: <span class="text-muted">[Adicionar email]</span></p>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

djangoapp/pihome/templates/pihome/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PiHome</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">

</head>

<body class="animate-page">

  <nav class="navbar navbar-dark bg-dark fixed-top no-animate">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'pihome:index' %}">PiHome</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
        aria-controls="offcanvasDarkNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
        aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
            aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" id="editButton" href="#">Editar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'pihome:pi_db_list' %}">API</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Informações
              </a>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><a class="dropdown-item" href="{% url 'pihome:project_info' %}">Projeto PiHome</a></li>
                <li><a class="dropdown-item" href="{% url 'pihome:group' %}">Grupo</a></li>
                <li><a class="dropdown-item" href="{% url 'pihome:license' %}">Licença</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'pihome:integrator_project' %}">Projeto Integrador Univesp</a>
                </li>
                <li>
                  <hr class="dropdown-divider">
                </li>
              </ul>
            </li>
          </ul>
          <a href="{% url 'account_logout' %}" class="logout-btn position-absolute bottom-0 end-0 mb-3 me-3">Logout</a>
        </div>
      </div>
    </div>
  </nav>

  <!-- <div class="container">
    <h2 id="pageTitle">Dispositivos</h2>
    <div class="button-group">
      <button id="addButton" class="primary-btn">+</button>
    </div>

    <div id="container" class="grid">
      {% for button in buttons %}
      <div class="button-container">
        <button class="dynamic-btn" data-id="{{ button.id }}" data-ip="{{ button.ip }}" data-port="{{ button.port }}"
          data-topic="{{ button.topic }}" data-message="{{ button.message }}">{{ button.name }}</button>
        <button class="edit-btn" style="display: none;">Editar</button>
        <button class="delete-btn" style="display: none;">Apagar</button>
      </div>
      {% endfor %}
    </div> -->

    <div class="container">
      <h2 id="pageTitle">Dispositivos</h2>
      <div class="button-group">
        <button id="addButton" class="primary-btn">+</button>
      </div>
  
      <div id="container" class="grid">
        {% for button in buttons %}
        <div class="button-container">
          <button class="dynamic-btn" data-id="{{ button.id }}" data-ip="{{ button.ip }}" data-port="{{ button.port }}"
            data-topic="{{ button.topic }}" data-message="{{ button.message }}">{{ button.name }}</button>
          <button class="edit-btn" style="display: none;">Editar</button>
          <button class="delete-btn" style="display: none;">Apagar</button>
        </div>
        {% endfor %}
      </div>






    <!-- Modal -->
    <div id="modal" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>
        <h3>Configurar MQTT</h3>
        <input type="text" id="brokerIP" placeholder="IP do Broker">
        <input type="number" id="brokerPort" placeholder="Porta">
        <input type="text" id="mqttTopic" placeholder="Tópico">
        <input type="text" id="buttonName" placeholder="Nome do Botão">
        <select id="messageMqtt">
          <option value="TOGGLE">Toggle</option>
          <option value="ON">On</option>
          <option value="OFF">Off</option>
          <option value="CUSTOM">Custom</option>
        </select>
        <input type="text" id="customMessage" placeholder="Mensagem Customizada" style="display: none;">
        <br><br>
        <button id="confirmButton" class="primary-btn">Salvar</button>
      </div>
    </div>

    <div id="noButtonsPopup" class="modal">
      <div class="modal-content">
        <span class="close">&times;</span>
        <h3>Atenção</h3>
        <p>Adicione um dispositivo primeiro clicando no botão "+" no canto inferior direito.</p>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

djangoapp/pihome/templates/pihome/license.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Licença</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">PiHome</a>
            <a href="{% url 'pihome:index' %}" class="btn btn-outline-light">Voltar</a>
        </div>
    </nav>

    <div class="container mt-5 pt-5">
        <h2 class="text-center mb-4">Licença</h2>
        <div class="row">
            <div class="col-12">
                <p>Esta aplicação é totalmente livre e sem fins lucrativos. Foi desenvolvida exclusivamente para fins de estudo e aprendizado.</p>
                <p>Você pode:</p>
                <ul>
                    <li>Baixar e usar a aplicação sem restrições.</li>
                    <li>Alterar o código para atender às suas necessidades.</li>
                    <li>Redistribuir a aplicação, incluindo suas alterações.</li>
                </ul>
                <p>Por favor, respeite o propósito educacional desta aplicação e compartilhe suas melhorias com a comunidade para que todos possam se beneficiar.</p>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>